#%RAML 0.8
---
title: Mixtio
baseUri: http://localhost
version: 2.0

traits:
  - pageable:
      queryParameters:
        page:
          displayName: page
          type: number
          description: The page you want
          example: 1
          required: false
        page_size:
          displayName: page_size
          type: number
          description: The number of results returned in a page
          example: 10
          required: false
  - sortable:
      queryParameters:
        sort:
          displayName: sort
          type: string
          description: Orders the collection by the field given (either created_at or updated_at). Default is ascending. Put a minus before the value for descending.
          example: |
            sort=created_at
            sort=-updated_at
          required: false

resourceTypes:
  - collection:
      get:
        is: [pageable, sortable]
        description: Get a list of <<resourcePathName>>.
        responses:
          200:
            body:
              application/json:
                example: |
                  <<exampleCollection>>
/batches:
  type:
    collection:
      exampleCollection: |
        {
           "data":[
              {
                 "id":"97",
                 "type":"batches",
                 "attributes":{
                    "number":"TESTTEAM-97",
                    "created_at":"2016-04-08T11:19:44.429Z",
                    "expiry_date":"2016-05-11",
                    "volume":"0.000259",
                    "unit":"L"
                 },
                 "relationships":{
                    "consumable_type":{
                       "data":{
                          "id":"31",
                          "type":"consumable_types"
                       }
                    },
                    "kitchen":{
                       "data":{
                          "id":"25",
                          "type":"teams"
                       }
                    },
                    "user":{
                       "data":{
                          "id":"1",
                          "type":"users"
                       }
                    },
                    "ingredients":{
                       "data":[

                       ]
                    },
                    "consumables":{
                       "data":[
                          {
                             "id":"171",
                             "type":"consumables"
                          },
                          {
                             "id":"172",
                             "type":"consumables"
                          },
                          {
                             "id":"173",
                             "type":"consumables"
                          },
                          {
                             "id":"174",
                             "type":"consumables"
                          },
                          {
                             "id":"175",
                             "type":"consumables"
                          }
                       ]
                    }
                 }
              },
              {
                 "id":"98",
                 "type":"batches",
                 "attributes":{
                    "number":"TESTTEAM-98",
                    "created_at":"2016-04-08T11:19:44.469Z",
                    "expiry_date":"2016-05-11",
                    "volume":"0.4655",
                    "unit":"L"
                 },
                 "relationships":{
                    "consumable_type":{
                       "data":{
                          "id":"32",
                          "type":"consumable_types"
                       }
                    },
                    "kitchen":{
                       "data":{
                          "id":"25",
                          "type":"teams"
                       }
                    },
                    "user":{
                       "data":{
                          "id":"1",
                          "type":"users"
                       }
                    },
                    "ingredients":{
                       "data":[

                       ]
                    },
                    "consumables":{
                       "data":[
                          {
                             "id":"176",
                             "type":"consumables"
                          },
                          {
                             "id":"177",
                             "type":"consumables"
                          },
                          {
                             "id":"178",
                             "type":"consumables"
                          },
                          {
                             "id":"179",
                             "type":"consumables"
                          },
                          {
                             "id":"180",
                             "type":"consumables"
                          },
                          {
                             "id":"181",
                             "type":"consumables"
                          },
                          {
                             "id":"182",
                             "type":"consumables"
                          }
                       ]
                    }
                 }
              }
           ],
           "included":[
              {
                 "id":"31",
                 "type":"consumable_types",
                 "attributes":{
                    "name":"IMDM",
                    "days_to_keep":33,
                    "storage_condition":null
                 }
              },
              {
                 "id":"25",
                 "type":"teams",
                 "attributes":{
                    "name":"TEST TEAM"
                 }
              },
              {
                 "id":"1",
                 "type":"users",
                 "attributes":{
                    "username":"test"
                 }
              },
              {
                 "id":"32",
                 "type":"consumable_types",
                 "attributes":{
                    "name":"F12 Nut Mix",
                    "days_to_keep":33,
                    "storage_condition":null
                 }
              }
           ],
           "links":{
              "self":"http://0.0.0.0:3000/api/v2/batches?page%5Bnumber%5D=1\u0026page%5Bsize%5D=2\u0026page_size=2",
              "next":"http://0.0.0.0:3000/api/v2/batches?page%5Bnumber%5D=2\u0026page%5Bsize%5D=2\u0026page_size=2",
              "last":"http://0.0.0.0:3000/api/v2/batches?page%5Bnumber%5D=15\u0026page%5Bsize%5D=2\u0026page_size=2"
           }
        }
  /{batch_id}:
    get:
      description: Retrieve a specific batch
      responses:
        200:
          body:
            application/json:
              example: |
                {
                   "data":{
                      "id":"97",
                      "type":"batches",
                      "attributes":{
                         "number":"TESTTEAM-97",
                         "created_at":"2016-04-08T11:19:44.429Z",
                         "expiry_date":"2016-05-11",
                         "volume":"0.000259",
                         "unit":"L"
                      },
                      "relationships":{
                         "consumable_type":{
                            "data":{
                               "id":"31",
                               "type":"consumable_types"
                            }
                         },
                         "kitchen":{
                            "data":{
                               "id":"25",
                               "type":"teams"
                            }
                         },
                         "user":{
                            "data":{
                               "id":"1",
                               "type":"users"
                            }
                         },
                         "ingredients":{
                            "data":[

                            ]
                         },
                         "consumables":{
                            "data":[
                               {
                                  "id":"171",
                                  "type":"consumables"
                               },
                               {
                                  "id":"172",
                                  "type":"consumables"
                               },
                               {
                                  "id":"173",
                                  "type":"consumables"
                               },
                               {
                                  "id":"174",
                                  "type":"consumables"
                               },
                               {
                                  "id":"175",
                                  "type":"consumables"
                               }
                            ]
                         }
                      }
                   },
                   "included":[
                      {
                         "id":"31",
                         "type":"consumable_types",
                         "attributes":{
                            "name":"IMDM",
                            "days_to_keep":33,
                            "storage_condition":null
                         }
                      },
                      {
                         "id":"25",
                         "type":"teams",
                         "attributes":{
                            "name":"TEST TEAM"
                         }
                      },
                      {
                         "id":"1",
                         "type":"users",
                         "attributes":{
                            "username":"test"
                         }
                      }
                   ]
                }
        404:
          body:
            application/json:
              example: |
                {
                  "message": "Couldn't find Batch with 'id'=123"
                }

/consumable_types:
  type:
    collection:
      exampleCollection: |
        {
           "data":[
              {
                 "id":"31",
                 "type":"consumable_types",
                 "attributes":{
                    "name":"IMDM",
                    "days_to_keep":33,
                    "storage_condition":null
                 }
              },
              {
                 "id":"32",
                 "type":"consumable_types",
                 "attributes":{
                    "name":"F12 Nut Mix",
                    "days_to_keep":33,
                    "storage_condition":null
                 }
              }
           ],
           "links":{
              "self":"http://0.0.0.0:3000/api/v2/consumable_types?page%5Bnumber%5D=1\u0026page%5Bsize%5D=2\u0026page_size=2",
              "next":"http://0.0.0.0:3000/api/v2/consumable_types?page%5Bnumber%5D=2\u0026page%5Bsize%5D=2\u0026page_size=2",
              "last":"http://0.0.0.0:3000/api/v2/consumable_types?page%5Bnumber%5D=15\u0026page%5Bsize%5D=2\u0026page_size=2"
           }
        }

  /{consumable_type_id}:
    get:
      description: Retrieve a specific consumable type
      responses:
        200:
          body:
            application/json:
              example: |
                {
                   "data":{
                      "id":"31",
                      "type":"consumable_types",
                      "attributes":{
                         "name":"IMDM",
                         "days_to_keep":33,
                         "storage_condition":null
                      }
                   }
                }
        404:
          body:
            application/json:
              example: |
                {
                  "message": "Couldn't find ConsumableType with 'id'=123"
                }

/consumables:
  get:
    is: [pageable, sortable]
    queryParameters:
      barcode:
        type: string
        description: The barcode of a Consumable
        example: MX-100
        required: false
    description: Get a list of Consumables.
    responses:
      200:
        body:
          application/json:
            example: |
              {
                 "data":[
                    {
                       "id":"171",
                       "type":"consumables",
                       "attributes":{
                          "created_at":"2016-04-08T11:19:44.440Z",
                          "barcode":"RGNT_171",
                          "volume":"51.8",
                          "unit":"μL",
                          "depleted":false
                       },
                       "relationships":{
                          "batch":{
                             "data":{
                                "id":"97",
                                "type":"batches"
                             }
                          },
                          "consumable_type":{
                             "data":{
                                "id":"31",
                                "type":"consumable_types"
                             }
                          }
                       }
                    },
                    {
                       "id":"172",
                       "type":"consumables",
                       "attributes":{
                          "created_at":"2016-04-08T11:19:44.446Z",
                          "barcode":"RGNT_172",
                          "volume":"51.8",
                          "unit":"μL",
                          "depleted":false
                       },
                       "relationships":{
                          "batch":{
                             "data":{
                                "id":"97",
                                "type":"batches"
                             }
                          },
                          "consumable_type":{
                             "data":{
                                "id":"31",
                                "type":"consumable_types"
                             }
                          }
                       }
                    }
                 ],
                 "included":[
                    {
                       "id":"31",
                       "type":"consumable_types",
                       "attributes":{
                          "name":"IMDM",
                          "days_to_keep":33,
                          "storage_condition":null
                       }
                    }
                 ],
                 "links":{
                    "self":"http://0.0.0.0:3000/api/v2/consumables?page%5Bnumber%5D=1\u0026page%5Bsize%5D=2\u0026page_size=2",
                    "next":"http://0.0.0.0:3000/api/v2/consumables?page%5Bnumber%5D=2\u0026page%5Bsize%5D=2\u0026page_size=2",
                    "last":"http://0.0.0.0:3000/api/v2/consumables?page%5Bnumber%5D=85\u0026page%5Bsize%5D=2\u0026page_size=2"
                 }
              }

  /{consumable_id}:
    get:
      description: Retrieve a specific consumable
      responses:
        200:
          body:
            application/json:
              example: |
                {
                   "data":{
                      "id":"171",
                      "type":"consumables",
                      "attributes":{
                         "created_at":"2016-04-08T11:19:44.440Z",
                         "barcode":"RGNT_171",
                         "volume":"51.8",
                         "unit":"μL",
                         "depleted":false
                      },
                      "relationships":{
                         "batch":{
                            "data":{
                               "id":"97",
                               "type":"batches"
                            }
                         },
                         "consumable_type":{
                            "data":{
                               "id":"31",
                               "type":"consumable_types"
                            }
                         }
                      }
                   },
                   "included":[
                      {
                         "id":"31",
                         "type":"consumable_types",
                         "attributes":{
                            "name":"IMDM",
                            "days_to_keep":33,
                            "storage_condition":null
                         }
                      }
                   ]
                }
        404:
          body:
            application/json:
              example: |
                {
                  "message": "Couldn't find Consumable"
                }

/lots:
  type:
    collection:
      exampleCollection: |
        {
           "data":[
              {
                 "id":"64",
                 "type":"lots",
                 "attributes":{
                    "number":"1695234"
                 },
                 "relationships":{
                    "consumable_type":{
                       "data":{
                          "id":"31",
                          "type":"consumable_types"
                       }
                    },
                    "kitchen":{
                       "data":{
                          "id":"27",
                          "type":"suppliers"
                       }
                    }
                 }
              },
              {
                 "id":"65",
                 "type":"lots",
                 "attributes":{
                    "number":"1696982"
                 },
                 "relationships":{
                    "consumable_type":{
                       "data":{
                          "id":"32",
                          "type":"consumable_types"
                       }
                    },
                    "kitchen":{
                       "data":{
                          "id":"28",
                          "type":"suppliers"
                       }
                    }
                 }
              }
           ],
           "included":[
              {
                 "id":"31",
                 "type":"consumable_types",
                 "attributes":{
                    "name":"IMDM",
                    "days_to_keep":33,
                    "storage_condition":null
                 }
              },
              {
                 "id":"27",
                 "type":"suppliers",
                 "attributes":{
                    "name":"LIFE TECH 21980-032"
                 }
              },
              {
                 "id":"32",
                 "type":"consumable_types",
                 "attributes":{
                    "name":"F12 Nut Mix",
                    "days_to_keep":33,
                    "storage_condition":null
                 }
              },
              {
                 "id":"28",
                 "type":"suppliers",
                 "attributes":{
                    "name":"LIFE TECH 31765-027"
                 }
              }
           ],
           "links":{
              "self":"http://0.0.0.0:3000/api/v2/lots?page%5Bnumber%5D=1\u0026page%5Bsize%5D=2\u0026page_size=2",
              "next":"http://0.0.0.0:3000/api/v2/lots?page%5Bnumber%5D=2\u0026page%5Bsize%5D=2\u0026page_size=2",
              "last":"http://0.0.0.0:3000/api/v2/lots?page%5Bnumber%5D=17\u0026page%5Bsize%5D=2\u0026page_size=2"
           }
        }
  /{lot_id}:
    get:
      description: Retrieve a specific lot
      responses:
        200:
          body:
            application/json:
              example: |
                {
                   "data":{
                      "id":"64",
                      "type":"lots",
                      "attributes":{
                         "number":"1695234"
                      },
                      "relationships":{
                         "consumable_type":{
                            "data":{
                               "id":"31",
                               "type":"consumable_types"
                            }
                         },
                         "kitchen":{
                            "data":{
                               "id":"27",
                               "type":"suppliers"
                            }
                         }
                      }
                   },
                   "included":[
                      {
                         "id":"31",
                         "type":"consumable_types",
                         "attributes":{
                            "name":"IMDM",
                            "days_to_keep":33,
                            "storage_condition":null
                         }
                      },
                      {
                         "id":"27",
                         "type":"suppliers",
                         "attributes":{
                            "name":"LIFE TECH 21980-032"
                         }
                      }
                   ]
                }
        404:
          body:
            application/json:
              example: |
                {
                  "message": "Couldn't find Lot with 'id'=123"
                }

/suppliers:
  type:
    collection:
      exampleCollection: |
        {
           "data":[
              {
                 "id":"27",
                 "type":"suppliers",
                 "attributes":{
                    "name":"LIFE TECH 21980-032"
                 }
              },
              {
                 "id":"28",
                 "type":"suppliers",
                 "attributes":{
                    "name":"LIFE TECH 31765-027"
                 }
              }
           ],
           "links":{
              "self":"http://0.0.0.0:3000/api/v2/suppliers?page%5Bnumber%5D=1\u0026page%5Bsize%5D=2\u0026page_size=2",
              "next":"http://0.0.0.0:3000/api/v2/suppliers?page%5Bnumber%5D=2\u0026page%5Bsize%5D=2\u0026page_size=2",
              "last":"http://0.0.0.0:3000/api/v2/suppliers?page%5Bnumber%5D=12\u0026page%5Bsize%5D=2\u0026page_size=2"
           }
        }
  /{supplier_id}:
    get:
      description: Retrieve a specific supplier
      responses:
        200:
          body:
            application/json:
              example: |
                {
                   "data":{
                      "id":"27",
                      "type":"suppliers",
                      "attributes":{
                         "name":"LIFE TECH 21980-032"
                      }
                   }
                }
        404:
          body:
            application/json:
              example: |
                {
                  "message": "Couldn't find Supplier with 'id'=123"
                }